services:
  - type: web
    name: imei-bot
    env: python
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: API_KEY
        sync: false  
      - key: AUTHORIZED_USER_IDS
        sync: false
      - key: RENDER_URL
        sync: false
      - key: KEEP_ALIVE_ENABLED
        value: true
      - key: KEEP_ALIVE_INTERVAL
        value: 840